version: '3.8'
services:
    striim-metadatarepo:
        image: "docker.io/striim/striim-dbms:latest"
        ports:
            - 1527:1527
        volumes:
            - striim-mdr:/var/striim

    striim-node:
        image: "docker.io/striim/striim-node:latest"
        depends_on:
            - striim-metadatarepo
        ports:
            - 9080
        env_file:
            - striim-node.env
        environment:
            STRIIM_METADATAREPO_ADDR: striim-metadatarepo:1527
        secrets:
            - admin_password
            - db_password
            - keystore_password
            - system_password
        volumes:
            - striim-extdata:/opt/striim/data
            - striim-extlibs:/opt/striim/extlib
            - striim-extes:/opt/striim/elasticsearch
#            - ./striim-conf/startUp.properties:/opt/striim/conf/startUp.properties.updated

secrets:
   admin_password:
     file: ./admpw
   db_password:
     file: ./dbpw
   keystore_password:
     file: ./kspw
   system_password:
     file: ./syspw
            
volumes:
    striim-extdata:
    striim-extlibs:
    striim-extes:
    striim-mdr:    
